name: "videotube-service"
services:
  videotube-nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp-container
    ports:
      - 3333:8000
    env_file:
      - .env.docker
    depends_on:
      - mongodb
    networks:
      - videotube-network

  mongodb:
    image: mongo
    container_name: videotube-mongodb
    ports:
      - 3700:27017
    env_file:
      - .env.docker
    networks:
      - videotube-network
    volumes:
      - videotube-data:/data/db

networks:
  videotube-network:
    driver: bridge

volumes:
  videotube-data:
    driver: local
